---
- hosts: [dbservers]
  become: true
  vars_files:
    - vars/vault.yml

  tasks:
    - name: "Mysql Configuration - Resetting RootPassword"
      mysql_user:
        login_host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root
        host: "%"
        password: "{{ mysql_root_password }}"
        state: present