---
- hosts: [syslogservers]
  become: true
  tasks:
    - name: "Install rsyslog on syslogserver(s)"
      apt:
        name: rsyslog
        update_cache: yes
        state: present

    - name: "UDP Activation"
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^(.)module(load="imudp")$'
        line: 'module(load="imudp")'

    - name: "UDP Port 514 Activation"
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^(.)input(type="imudp" port="514")$'
        line: 'input(type="imudp" port="514")'

    - name: "TCP Activation"
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^(.)module(load="imtcp")$'
        line: 'module(load="imtcp")'

    - name: "TCP 10514 Activation"
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^(.)input(type="imtcp" port="514")$'
        line: 'input(type="imtcp" port="10514")'

    - name: "Syslog service reboot"
      service:
        name: rsyslog
        state: restarted

- hosts: [webservers, dbservers]
  become: true
  tasks:
    - name: "Install rsyslog on client servers"
      apt:
        name: rsyslog
        update_cache: yes
        state: present

    - name: "Modify rsyslog.conf to add syslogserver "
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        line: '*.* @{{ hostvars[item].ansible_default_ipv4.address }}:514'
      with_items: "{{groups['syslogservers']}}"

    - name: "Syslog service reboot"
      service:
        name: rsyslog
        state: restarted

    - name: "Logger test"
      shell: 'logger -p local0.err "Les logs de "{{ item }}" sont bien redirigés vers le serveur Syslog."'
      with_items:
        - "{{groups['webservers']}}"
