---
- hosts: dbserver2
  become: true

  tasks:
    - name: "Create empty glpi database"
      community.mysql.mysql_db:
        login_user: root
        login_password: root
        name:
          - glpi
        state: present


- hosts: [dbservers]
  become: true

  tasks:

    - name: "Create replication_user inside of the database"
      community.mysql.mysql_query:
        login_user: root
        login_db: glpi
        login_password: root
        query: CREATE USER IF NOT EXISTS 'replication_user'@'%' IDENTIFIED BY 'rep';

    - name: "Grant REPLICATION SLAVE privileges"
      community.mysql.mysql_query:
        login_user: root
        login_db: glpi
        login_password: root
        query: GRANT REPLICATION SLAVE ON *.* TO 'replication_user'@'%';

    - name: "Grant SUPER PRIVILEGES on root remote account"
      community.mysql.mysql_query:
        login_user: root
        login_db: glpi
        login_password: root
        query: GRANT SUPER ON *.* TO 'root'@'%';

    - name: "Restart mysql service"
      service:
        name: mysql
        state: restarted

    - name: "Grant REPLICATION SLAVE privileges"
      community.mysql.mysql_query:
        login_user: root
        login_db: glpi
        login_password: root
        query: GRANT REPLICATION SLAVE ON *.* TO 'replication_user'@'%';
        positional_args:

    - block:

      - name: "Get master status"
        community.mysql.mysql_query:
          login_user: root
          login_db: glpi
          login_password: root
          query: SHOW MASTER STATUS;
        register: File
      - debug:
          msg: "{{ item }}"
        with_items:
          - "{{ File }}"
        when: mysql_server_id==1

      - name: "Stop slave"
        community.mysql.mysql_query:
          login_user: root
          login_host: dbserver2
          login_password: root
          query: STOP SLAVE;
        when: mysql_server_id==2


      - name: "Change master to"
        community.mysql.mysql_query:
          login_user: root
          login_db: glpi
          login_password: root
          query: CHANGE MASTER TO MASTER_HOST='dbserver1', MASTER_USER='replication_user', MASTER_PASSWORD='rep', MASTER_PORT=3306, MASTER_LOG_FILE='{{ item.file }}', MASTER_LOG_POS={{ item.position }}, MASTER_CONNECT_RETRY=10;
          positional_args:
        when: mysql_server_id==2
        with_items:
          - file: "{{ hostvars['dbserver1']['File'].query_result[0][0].File}}"
            position: "{{ hostvars['dbserver1']['File'].query_result[0][0].Position}}"

      - name: "Stop slave"
        community.mysql.mysql_query:
          login_user: root
          login_host: dbserver2
          login_password: root
          query: START SLAVE;
        when: mysql_server_id==2