---
- hosts: [dbservers]
  become: true

  tasks:

    - name: "Check if root password is unset"
      shell: >
        mysql -u root
        -h localhost
        -S /var/run/mysqld/mysqld.sock
        -e "quit"
      changed_when: false
      ignore_errors: true
      register: root_pwd_check
      tags: mariadb

    - name: "Check if the specified root password is already set"
      shell: >
        mysqladmin -u root -p{{ mysql_root_password }} status
      changed_when: false
      no_log: true
      when: root_pwd_check.rc != 0
      tags: mariadb

    - name: "Check for previously set unix_socket in plugin column"
      command: >
        mysql -N -s -S /var/run/mysqld/mysqld.sock -u root -e
        "SELECT plugin from mysql.user WHERE user = 'root'"
      register: plugin_root_result
      changed_when: plugin_root_result.stdout is search('unix_socket')
      when: root_pwd_check.rc == 0
      tags: mariadb

    - name: "Set MariaDB root password for the first time"
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      tags: mariadb
